version: '3'
services:
  login:
    build: ./backend/login/
    restart: on-failure:2
    env_file:
      - ./backend/login/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rabbitmq-network
  canje:
    build: ./backend/canje/
    env_file:
      - ./backend/canje/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - rabbitmq-network  

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - ./backend/login/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-canjexpress-login:/var/lib/postgresql
    networks:
      - rabbitmq-network

  extraccion_datos:
    build: ./backend/extraccion_datos/
    env_file:
      - ./backend/extraccion_datos/.env
    depends_on:
      - db
    networks:
      - rabbitmq-network
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - rabbitmq-network

  front:
    build: 
      context: ./frontend/
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "80:80"
    networks:
      - rabbitmq-network
    depends_on:
      - login

volumes:
  db-canjexpress-login:
  rabbitmq-data:

networks:
  rabbitmq-network:
