version: '3'
services:
  login:
    build: ./backend/login/
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - rabbitmq-network
  canje:
    build: ./backend/canje/
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db
      - rabbitmq
    networks:
      - rabbitmq-network  

  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "canjexpress"
    ports:
      - "5432:5432"
    volumes:
      - db-canjexpress-login:/var/lib/postgresql
    networks:
      - rabbitmq-network

  extraccion_datos:
    build: ./backend/extraccion_datos/
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
    depends_on:
      - db
      - login
    networks:
      - rabbitmq-network
  
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - rabbitmq-network

  nginx:
    build: ./nginx/
    ports:
      - "8080:80"
    networks:
      - rabbitmq-network
    depends_on:
      - front
      - login
      - canje

  front:
    build: 
      context: ./frontend/
      args:
        VITE_API_URL: http://localhost:8080/api
    ports:
      - "80:80"
    networks:
      - rabbitmq-network
    depends_on:
      - login

volumes:
  db-canjexpress-login:
  rabbitmq-data:

networks:
  rabbitmq-network:
