version: '3'
services:
  login:
    build: ./login/
    restart: on-failure
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: 3000
      FLASK_ENV: "development"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend-network
  canje:
    build: ./canje/
    restart: on-failure
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: 3001
      FLASK_ENV: "development"
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - backend-network
  productos_puntos:
    build: ./productos_puntos/
    restart: on-failure
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_NAME: "canjexpress"
      DB_USER: "user"
      DB_PASSWORD: "password"
      PORT: 3002
      FLASK_ENV: "development"
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - backend-network

  db:
    image: postgres:16.0-alpine3.18
    restart: on-failure
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'canjexpress'
    ports:
      - "5432:5432"
    volumes:
      - db-canjexpress:/var/lib/postgresql
    networks:
      - backend-network

  extraccion_datos:
    build: ./extraccion_datos/
    environment:
      TABLE_NAME: "data"
      DATABASE_HOST: "db"
      DATABASE_DB: "canjexpress"
      DATABASE_USER: "user"
      DATABASE_PASSWORD: "password"
    networks:
      - backend-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - backend-network

  nginx:
    build: ./nginx/
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - backend-network
    depends_on:
      - login
      - canje
      - productos_puntos

volumes:
  db-canjexpress:
  rabbitmq-data:

networks:
  backend-network:
