version: '3'
services:
  login:
    build: ./login/
    restart: always
    environment:
      DB_HOST: "34.135.17.142"
      DB_PORT: 5432
      DB_NAME: "usuarios"
      DB_USER: "postgres"
      DB_PASSWORD: "PassArquiDB"
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - backend-network

  backoffice:
    build: ./backoffice/
    restart: on-failure
    environment:
      DB_HOST: "34.135.17.142"
      DB_PORT: 5432
      DB_NAME: "usuarios"
      DB_USER: "postgres"
      DB_PASSWORD: "PassArquiDB"
      PORT: 3000
      FLASK_ENV: "development"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - backend-network            
  canje:
    build: ./canje/
    restart: always
    environment:
      DB_HOST: "34.135.17.142"
      DB_PORT: 5432
      DB_NAME: "canje"
      DB_USER: "postgres"
      DB_PASSWORD: "PassArquiDB"
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - backend-network

  extraccion_datos:
    build: ./extraccion_datos/
    environment:
      TABLE_NAME: "data"
      DATABASE_HOST: "34.135.17.142"
      DATABASE_DB: "data"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "PassArquiDB"
    networks:
      - backend-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    networks:
      - backend-network

  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "80:80"
    networks:
      - backend-network
    depends_on:
      - login
      - canje

volumes:
  rabbitmq-data:

networks:
  backend-network:
