apiVersion: v1
kind: ConfigMap
metadata:
  name: config-login
data:
  FLASK_SECRET_KEY: "your_secret_key"
  DB_NAME: "mydatabase"
  DB_USER: "myuser"
  DB_PASSWORD: "mypassword"
  DB_HOST: "service-database"
  DB_PORT: "5432"

