apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-login
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
        - name: login
          image: luiggip/g5_arqui_login:latest
          envFrom:
            - configMapRef:
                name: config-login
