version: '3'
services:
  api:
    build: .
    environment:
      DB_USER: 'user'
      DB_PASSWORD: 'password'
      DB_HOST: 'db'
      DB_PORT: '5432'
      DB_NAME: 'canjexpress'
      PORT: '3002'
    ports:
      - "3002:3002"
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'canjexpress'
    ports:
      - "5432:5432"
    volumes:
      - db-canjexpress-productos-puntos:/var/lib/postgresql

volumes:
  db-canjexpress-productos-puntos:
